### ISSUE TITLE
The "install.cmd" stuck in the loop of request for privilege.

### ISSUE THREAD

**Issue by DavidLogic** [WSA-Community/WSAPackagingTool#1]
I followed the video carefully, but when I ran the "install.cmd" , the problem appeared. It always stuck in the loop.  I checked the source , I think that here is something wrong :
`%PS% Start-Process -Verb runAs -FilePath '"%~0"' -ArgumentList 'am_admin %CMD_LINE%'`

My Enviorment is Windows 11 , using tradtion Console.

Thanks!

**Comment by hideandseekstheorder** [comment]
me too

**Comment by MlgmXyysd** [comment]
Have you checked whether PowerShell is working properly?

**Comment by MlgmXyysd** [comment]
Change `@echo off` to `@echo on` and send the output here

**Comment by DavidLogic** [comment]
I downloaded it and in the Microsoft store. I am sure the PowerShell worked correctly.

**Comment by hideandseekstheorder** [comment]
still looping 
![image](https://user-images.githubusercontent.com/24226435/152285011-42a25d9f-97f3-432d-ab26-fb664ac3c311.png)

**Comment by MlgmXyysd** [comment]
hmmm, double quote

**Comment by MlgmXyysd** [comment]
try https://github.com/WSA-Community/WSAPackagingTool/commit/971a9c765eb9a2a75bde6fc83bf5340108abeabd

**Comment by hideandseekstheorder** [comment]
Install - WSAPackagingTool v1.0 By MlgmXyysd
https://github.com/WSA-Community/WSAPackagingTool
*********************************************

[#] Error: You need specify a valid Msixbundle package.
Press any key to continue . . .

**Comment by hideandseekstheorder** [comment]
still got error :(

**Comment by MlgmXyysd** [comment]
> still got error :(

drag msixbundle to install utility

**Comment by hideandseekstheorder** [comment]
where the to install utility locate ?

**Comment by MlgmXyysd** [comment]
> where the to install utility locate ?

it's `install.cmd`

**Comment by hideandseekstheorder** [comment]
Okay, its working, thanks @MlgmXyysd

**Comment by hideandseekstheorder** [comment]
![image](https://user-images.githubusercontent.com/24226435/152285919-abccb19d-2044-47c9-9b8b-3e42274b2248.png)

**Comment by hideandseekstheorder** [comment]
something wrong there, can u solve it sir ?

**Comment by MlgmXyysd** [comment]
> ![image](https://user-images.githubusercontent.com/24226435/152285919-abccb19d-2044-47c9-9b8b-3e42274b2248.png)

This is a problem with the package, and it has nothing to do with this issue. You may need to move to https://github.com/WSA-Community/WSAPackagingTool/issues/2#issuecomment-1028611604

**Comment by MlgmXyysd** [comment]
Fixed https://github.com/WSA-Community/WSAPackagingTool/commit/971a9c765eb9a2a75bde6fc83bf5340108abeabd
