### ISSUE TITLE
The "repack.cmd" cannot put x64 architecture into the msixbundle.

### ISSUE THREAD

**Issue by DavidLogic** [WSA-Community/WSAPackagingTool#2]
![problem](https://user-images.githubusercontent.com/58322362/152137530-d0b6fa5a-f836-4462-9c65-7ef0eae5ec73.jpg)

**Comment by MlgmXyysd** [comment]
It may be at the top. Or check the repack output. Msix may fail to pack

**Comment by DavidLogic** [comment]
No. I'm sorry the picture can't reflect my problem completely. I checked several times，but in vain.

**Comment by MlgmXyysd** [comment]
You can try to record the log output of repack. I suspect x64 has problems in the msix packaging process

**Comment by DavidLogic** [comment]
OK，I will try it later.

**Comment by hideandseekstheorder** [comment]
Processing "\\?\C:\WSAPackagingTool-master\temp\WsaPackage_1.8.32836.0_x64_Release-Nightly.msix_ext\WsaSettingsBroker\WsaSettingsBroker.exe" as a payload file.  Its path in the package will be "WsaSettingsBroker\WsaSettingsBroker.exe".
Processing "\\?\C:\WSAPackagingTool-master\temp\WsaPackage_1.8.32836.0_x64_Release-Nightly.msix_ext\wslcore.dll" as a payload file.  Its path in the package will be "wslcore.dll".
Processing "\\?\C:\WSAPackagingTool-master\temp\WsaPackage_1.8.32836.0_x64_Release-Nightly.msix_ext\wsldeps.dll" as a payload file.  Its path in the package will be "wsldeps.dll".
Processing "\\?\C:\WSAPackagingTool-master\temp\WsaPackage_1.8.32836.0_x64_Release-Nightly.msix_ext\wsldevicehost.dll" as a payload file.  Its path in the package will be "wsldevicehost.dll".
Processing "\\?\C:\WSAPackagingTool-master\temp\WsaPackage_1.8.32836.0_x64_Release-Nightly.msix_ext\wslhost.exe" as a payload file.  Its path in the package will be "wslhost.exe".
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x8007000e - Not enough memory resources are available to complete this operation.

**Comment by hideandseekstheorder** [comment]
![image](https://user-images.githubusercontent.com/24226435/152287330-3f860449-dfa0-4b4c-bda5-405edb97a356.png)

**Comment by hideandseekstheorder** [comment]
this is the log

**Comment by MlgmXyysd** [comment]
Out of memory, upgrade your computer hardware or kill some background programs

**Comment by hideandseekstheorder** [comment]
ohh thats the problem, thank you

**Comment by MlgmXyysd** [comment]
It has nothing to do with this tool. Maybe I should add a judgment on whether the packaging is successful or not.

**Comment by hideandseekstheorder** [comment]
> Maybe I should add a judgment on whether the packaging is successful or not.

it is very important in a program, hopefully in the future there will be

**Comment by mozilla343** [comment]
Great news! I just did fresh install of Windows 10 (yes, 10 not 11) 32-bit in Hyper-V. And guess what repack.cmd did its job without any errors. Now both ARM64 and x64 modified msixes are now included in msixbundle. :)

**Comment by MlgmXyysd** [comment]
> Great news! I just did fresh install of Windows 10 (yes, 10 not 11) 32-bit in Hyper-V. And guess what repack.cmd did its job without any errors. Now both ARM64 and x64 modified msixes are now included in msixbundle. :)

There is another possibility. For compatibility reasons, the built-in toolset is 32-bit, which cannot access too large byte-addressable memory (4GiB max). Replacing it with the corresponding architecture may solve the problem.
https://github.com/WSA-Community/WSAPackagingTool/tree/master/libraries#info

**Comment by MlgmXyysd** [comment]
multi architecture support is planned
https://github.com/WSA-Community/WSAPackagingTool#to-dos
