### ISSUE TITLE
Install.cmd does not work if a space is in the path.

### ISSUE THREAD

**Issue by adfwhitestar** [WSA-Community/WSAPackagingTool#4]
I was noticing that when I would use this install.cmd if the .msixbundle file is in a folder path that has a space in it. The script will fail.
After echoing what was set to the PACKAGE variable if you pass a file 
AKA. 
C:\mypath\with space\WSA.msixbundle

The Script will only grab the everything up to the space.

C:\mypath\with

Therefore would get caught in your '[#] Error: You need specify a valid Msixbundle package.' only after echoing the PACKAGE variable I noticed that what was happening.

This also gets worse if you add multiple spaces in the path name.
A path with two spaces 
C:\my path\with space\WSA.msixbundle

will become 
C:\my
path\with
space\WSA.msixbundle

and so on.

I was unable to find a way around this other then removing the spaces. If it is a limitation of the script maybe echo the path or tell the user that they need to remove all spaces from the path.

**Comment by JuryA** [comment]
I suggest replacing the Cmd batch with a PowerShell script. Life will be easier.

**Comment by MlgmXyysd** [comment]
Dragging the file into cmd is the correct way to install it, as Windows will append quotes automatically. If you are using the command line, then you will need to add the quotes yourself.
